#!/bin/bash
#
#VAR1=$(echo $WATER | tr 'water' '12345')
#echo $VAR1
#VAR2=$(echo $STIR | tr 'stir.' '12345')
#echo $VAR2
#RES1=$(($VAR1 + $VAR2))
#echo $RES1
#printf "%o\n" $(($#`echo $WATER | tr 'water' '01234'` + $#`echo $STIR | tr 'sti' '01234'`)) | tr '01234567' 'bestchol'
printf "%o\n" $(( $((5#$(echo $WATER | tr water 01234))) + $((5#$(echo $STIR | tr stir. 01234))) )) | tr 01234567 bestchol
